// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generate-version.ts from package.json

/**
 * Version information structure
 */
export interface VersionInfo {
  readonly major: number;
  readonly minor: number;
  readonly patch: number;
  readonly prerelease: string | undefined;
}

/**
 * Version string from package.json
 */
export const VERSION = '0.4.5';

/**
 * Parsed version components
 */
export const VERSION_INFO: VersionInfo = {
  major: 0,
  minor: 4,
  patch: 5,
  prerelease: undefined,
};
