packages:
  - 'packages/core'
  - 'packages/cli'
  - 'packages/ext/*'
  - 'packages/shared/*'
  - 'packages/fiddle'
  - 'packages/web'
  - 'packages/compose'
  - 'packages/host'
  - 'packages/registry-client'
  - 'demo/*'
