packages:
  - 'packages/core'
  - 'packages/cli'
  - 'packages/ext/*'
  - 'packages/shared/*'
  - 'packages/fiddle'
  - 'packages/web'
  - 'packages/compose'
  - 'packages/host'
  - 'packages/state-fs'
  - 'packages/state-sqlite'
  - 'packages/state-redis'
  - 'demo/*'
