#!/usr/bin/env -S pnpm exec tsx
/**
 * Generate the full LLM reference bundle from its source fragments
 *
 * Reads the 8 fragments listed in docs/ref-llms.txt, in the canonical order
 * that index enumerates them, and concatenates them (with a fixed preamble
 * and a consistent separator) into docs/ref-llms-full.txt.
 *
 * Usage:
 *   pnpm exec tsx packages/core/scripts/generate-llms-full.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const FRAGMENTS_DIR = 'docs/llm';
const OUTPUT_FILE = 'docs/ref-llms-full.txt';

// Canonical order per docs/ref-llms.txt's fragment table.
const FRAGMENT_ORDER = [
  'cheatsheet',
  'anti-patterns',
  'control-flow',
  'errors',
  'types',
  'callables',
  'stdlib',
  'style',
];

const SEPARATOR = '\n\n---\n\n';

const PREAMBLE = `<!-- AUTO-GENERATED - DO NOT EDIT. Generated by packages/core/scripts/generate-llms-full.ts from the fragments listed in docs/ref-llms.txt. -->

# rill

> Scripting language designed for machine-generated code. LLMs generate rill scripts; humans review and debug. Data flows through pipes (\`->\`), not assignment. Variables use \`$\` prefix. No null, no exceptions, no truthiness.

For progressive disclosure, see [ref-llms.txt](ref-llms.txt) (index) and [llm/*.txt](llm/) fragments. This file is the full single-source bundle.`;

export function buildLlmsFullContent(projectRoot: string): string {
  const fragmentsDir = path.join(projectRoot, FRAGMENTS_DIR);

  const fragments = FRAGMENT_ORDER.map((name) => {
    const fragmentPath = path.join(fragmentsDir, `${name}.txt`);
    if (!fs.existsSync(fragmentPath)) {
      console.error(`ERROR: Fragment not found: ${fragmentPath}`);
      process.exit(1);
    }
    return fs.readFileSync(fragmentPath, 'utf-8').replace(/\n+$/, '');
  });

  return [PREAMBLE, ...fragments].join(SEPARATOR) + '\n';
}

function main(): void {
  const coreDir = path.resolve(
    path.dirname(new URL(import.meta.url).pathname),
    '..'
  );
  const projectRoot = path.resolve(coreDir, '..', '..');
  const outputPath = path.join(projectRoot, OUTPUT_FILE);

  const content = buildLlmsFullContent(projectRoot);

  fs.writeFileSync(outputPath, content, 'utf-8');

  console.log(
    `Generated ${OUTPUT_FILE} from ${FRAGMENT_ORDER.length} fragments in ${FRAGMENTS_DIR}`
  );
  console.log(`Content length: ${content.length} characters`);
}

main();
