#!/usr/bin/env -S pnpm exec tsx
/**
 * Generate the full LLM reference bundle from its source fragments
 *
 * Reads the 8 fragments listed in docs/ref-llms.txt, in the canonical order
 * that index enumerates them, and concatenates them (with a fixed preamble
 * and a consistent separator) into docs/ref-llms-full.txt.
 *
 * docs/ref-llms-full.txt is a checked-in artifact, not part of the build
 * pipeline: tests/ref-llms-full-drift.test.ts asserts the committed file
 * matches the fragments. Run this script manually after editing a fragment
 * under docs/llm/, then commit the regenerated bundle.
 *
 * Usage:
 *   pnpm --filter @rcrsr/rill run docs:llms-full
 */

import * as fs from 'fs';
import * as path from 'path';
import { resolveProjectRoot } from './resolve-project-root.js';

const FRAGMENTS_DIR = 'docs/llm';
const OUTPUT_FILE = 'docs/ref-llms-full.txt';

// Canonical order per docs/ref-llms.txt's fragment table.
const FRAGMENT_ORDER = [
  'cheatsheet',
  'anti-patterns',
  'control-flow',
  'errors',
  'types',
  'callables',
  'stdlib',
  'style',
];

const SEPARATOR = '\n\n---\n\n';

const PREAMBLE = `<!-- AUTO-GENERATED - DO NOT EDIT. Generated by packages/core/scripts/generate-llms-full.ts from the fragments listed in docs/ref-llms.txt. -->

# rill

> Scripting language designed for machine-generated code. LLMs generate rill scripts; humans review and debug. Data flows through pipes (\`->\`), not assignment. Variables use \`$\` prefix. No null, no exceptions, no truthiness.

For progressive disclosure, see [ref-llms.txt](ref-llms.txt) (index) and [llm/*.txt](llm/) fragments. This file is the full single-source bundle.`;

export function buildLlmsFullContent(projectRoot: string): string {
  const fragmentsDir = path.join(projectRoot, FRAGMENTS_DIR);

  const fragments = FRAGMENT_ORDER.map((name) => {
    const fragmentPath = path.join(fragmentsDir, `${name}.txt`);
    if (!fs.existsSync(fragmentPath)) {
      throw new Error(`Fragment not found: ${fragmentPath}`);
    }
    return fs.readFileSync(fragmentPath, 'utf-8').replace(/\n+$/, '');
  });

  return [PREAMBLE, ...fragments].join(SEPARATOR) + '\n';
}

function main(): void {
  const coreDir = resolveProjectRoot(import.meta.url);
  const projectRoot = path.resolve(coreDir, '..', '..');
  const outputPath = path.join(projectRoot, OUTPUT_FILE);

  const content = buildLlmsFullContent(projectRoot);

  fs.writeFileSync(outputPath, content, 'utf-8');

  console.log(
    `Generated ${OUTPUT_FILE} from ${FRAGMENT_ORDER.length} fragments in ${FRAGMENTS_DIR}`
  );
  console.log(`Content length: ${content.length} characters`);
}

// Only run as a side effect when executed directly (`tsx generate-llms-full.ts`),
// not when tests/ref-llms-full-drift.test.ts imports buildLlmsFullContent —
// otherwise the import would overwrite the committed bundle before the test
// compares against it.
if (import.meta.filename === process.argv[1]) {
  try {
    main();
  } catch (e) {
    console.error(`ERROR: ${e instanceof Error ? e.message : String(e)}`);
    process.exit(1);
  }
}
