#!/usr/bin/env -S pnpm exec tsx
/**
 * Generate version data from package.json for runtime introspection
 *
 * Reads package.json version field and generates
 * src/generated/version-data.ts with a VERSION constant.
 *
 * Usage:
 *   pnpm exec tsx packages/service/scripts/generate-version.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const PACKAGE_JSON = 'package.json';
const OUTPUT_FILE = 'src/generated/version-data.ts';

function main(): void {
  const rootDir = path.resolve(
    path.dirname(new URL(import.meta.url).pathname),
    '..'
  );
  const packagePath = path.join(rootDir, PACKAGE_JSON);
  const outputPath = path.join(rootDir, OUTPUT_FILE);

  // Check package.json exists
  if (!fs.existsSync(packagePath)) {
    console.error(`ERROR: package.json not found: ${packagePath}`);
    process.exit(1);
  }

  // Read and parse package.json
  const packageContent = fs.readFileSync(packagePath, 'utf-8');
  const packageData = JSON.parse(packageContent) as {
    version?: string;
    [key: string]: unknown;
  };

  // Check version field exists
  if (!packageData.version) {
    console.error('ERROR: package.json missing version field');
    process.exit(1);
  }

  const version = packageData.version;

  // Generate output
  const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by packages/service/scripts/generate-version.ts from ${PACKAGE_JSON}

/**
 * Version string from package.json
 */
export const VERSION = '${version}';
`;

  // Ensure output directory exists
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  // Write output file
  fs.writeFileSync(outputPath, output, 'utf-8');

  console.log(`Generated ${OUTPUT_FILE} from ${PACKAGE_JSON}`);
  console.log(`Version: ${version}`);
}

main();
