/**
 * AST Type Unions
 * String union of all AST node type literals.
 */

// ============================================================
// NODE TYPE STRING UNION
// ============================================================

export type NodeType =
  | 'Script'
  | 'Frontmatter'
  | 'Closure'
  | 'ClosureParam'
  | 'Statement'
  | 'PipeChain'
  | 'PostfixExpr'
  | 'MethodCall'
  | 'Invoke'
  | 'AnnotationAccess'
  | 'HostCall'
  | 'HostRef'
  | 'ClosureCall'
  | 'PipeInvoke'
  | 'Variable'
  | 'Capture'
  | 'Conditional'
  | 'WhileLoop'
  | 'DoWhileLoop'
  | 'Block'
  | 'StringLiteral'
  | 'Interpolation'
  | 'NumberLiteral'
  | 'BoolLiteral'
  | 'ListSpread'
  | 'Dict'
  | 'DictEntry'
  | 'Break'
  | 'Return'
  | 'Yield'
  | 'Pass'
  | 'Assert'
  | 'BinaryExpr'
  | 'UnaryExpr'
  | 'GroupedExpr'
  | 'Destructure'
  | 'DestructPattern'
  | 'Slice'
  | 'TypeAssertion'
  | 'TypeCheck'
  | 'AnnotatedStatement'
  | 'AnnotatedExpr'
  | 'NamedArg'
  | 'SpreadArg'
  | 'EachExpr'
  | 'MapExpr'
  | 'FoldExpr'
  | 'FilterExpr'
  | 'RecoveryError'
  | 'Error'
  | 'TypeNameExpr'
  | 'TypeConstructor'
  | 'ClosureSigLiteral'
  | 'ListLiteral'
  | 'DictLiteral'
  | 'TupleLiteral'
  | 'OrderedLiteral'
  | 'Destruct'
  | 'Convert'
  | 'UseExpr';
