/**
 * Rill Module
 * Exports lexer, parser, runtime, and AST types
 */

export { LexerError, tokenize, type TokenizeOptions } from './lexer/index.js';
export {
  parse,
  parseWithRecovery,
  parseTypeRef,
  createParserState,
  type ParserState,
} from './parser/index.js';
export type { ParseResult, RecoveryErrorNode, ErrorNode } from './types.js';
export {
  anyTypeValue,
  type ApplicationCallable,
  atomName,
  BreakSignal,
  BUILT_IN_TYPES,
  BUILTIN_METHODS,
  buildFieldDescriptor,
  callable,
  type CallableFn,
  type CallFrame,
  commonType,
  compareStructuredFields,
  type CaptureEvent,
  type ConfigFieldDescriptor,
  contextResolver,
  copyValue,
  createOrdered,
  createRillStream,
  createRuntimeContext,
  createStepper,
  createTestContext,
  createTuple,
  createVector,
  deepEquals,
  deserializeValue,
  type DocumentationCoverageResult,
  emitExtensionEvent,
  type ErrorEvent,
  execute,
  type ExecutionResult,
  type ExecutionStepper,
  ExtensionBindingError,
  type ExtensionConfigSchema,
  type ExtensionEvent,
  type ExtensionFactory,
  type ExtensionFactoryCtx,
  type ExtensionFactoryResult,
  type ExtensionManifest,
  extResolver,
  type FieldComparisonCallbacks,
  formatHalt,
  formatRillLiteral,
  formatStructure,
  formatValue,
  type FunctionMetadata,
  type FunctionReturnEvent,
  generateManifest,
  getCallStack,
  getDocumentationCoverage,
  getFunctions,
  getLanguageReference,
  getStatus,
  type HandlerMetadataStatic,
  type HandlerParamStatic,
  type HostCallEvent,
  hydrateFieldDefaults,
  inferElementType,
  inferStructure,
  inferType,
  introspectHandlerFromAST,
  type InvalidateMeta,
  type InvalidMeta,
  invokeCallable,
  isApplicationCallable,
  isCallable,
  isDatetime,
  isDict,
  isDuration,
  isEmpty,
  isInvalid,
  isIterator,
  isReservedMethod,
  isRillStream,
  isRuntimeCallable,
  isScriptCallable,
  isStream,
  isTruthy,
  isTuple,
  isTypeValue,
  isVacant,
  isVector,
  marshalArgs,
  type MarshalOptions,
  moduleResolver,
  type NativeArray,
  type NativePlainObject,
  type NativeResult,
  type NativeValue,
  type ObservabilityCallbacks,
  type ParamMetadata,
  paramToFieldDef,
  popCallFrame,
  pushCallFrame,
  RESERVED_DICT_METHODS,
  resolveAtom,
  type ResolverResult,
  ReturnSignal,
  RuntimeHaltSignal,
  YieldSignal,
  type RillCallable,
  type RillCode,
  type RillDatetime,
  type RillDuration,
  type RillFieldDef,
  type RillFunction,
  type RillIterator,
  type RillParam,
  type RillStatus,
  type RillStream,
  type RillTuple,
  type RillTypeValue,
  type RillValue,
  type RillVector,
  type RuntimeCallable,
  type RuntimeCallbacks,
  type RuntimeContext,
  type RuntimeOptions,
  type SchemeResolver,
  type ScriptCallable,
  serializeValue,
  type StepEndEvent,
  type StepResult,
  type StepStartEvent,
  structureEquals,
  structureMatches,
  structureToTypeValue,
  toCallable,
  toNative,
  type TraceFrame,
  type TraceKind,
  type TypeDefinition,
  type TypeProtocol,
  type TypeStructure,
  VERSION,
  VERSION_INFO,
  type VersionInfo,
} from './runtime/index.js';

// ============================================================
// ERROR TAXONOMY
// ============================================================
export {
  type ErrorCategory,
  type ErrorDefinition,
  type ErrorSeverity,
  ERROR_REGISTRY,
  renderMessage,
  getHelpUrl,
  createError,
} from './types.js';

// ============================================================
// ERROR FORMATTING
// ============================================================
export {
  formatRillError,
  formatRillErrorJson,
  type FormatErrorOptions,
  type FormatErrorJsonOptions,
  type SourceMap,
} from './error-formatter.js';

// ============================================================
// SYNTAX HIGHLIGHTING
// ============================================================
export {
  type HighlightCategory,
  TOKEN_HIGHLIGHT_MAP,
} from './highlight-map.js';

export * from './types.js';
