/**
 * Tests for template rendering module.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  renderTemplate,
  FileSystemError,
  TemplateError,
} from '../src/templates.js';

// ============================================================
// TEST SETUP
// ============================================================

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const TEMPLATES_DIR = join(__dirname, '..', 'templates');

beforeAll(async () => {
  // Create templates directory for tests
  await mkdir(TEMPLATES_DIR, { recursive: true });

  // Create test templates
  await writeFile(
    join(TEMPLATES_DIR, 'simple.tmpl'),
    'Hello {{name}}!',
    'utf-8'
  );

  // Note: package.json.tmpl is a real template file, not a test fixture

  await writeFile(
    join(TEMPLATES_DIR, 'conditional.tmpl'),
    '{{#if enabled}}Feature enabled{{else}}Feature disabled{{/if}}',
    'utf-8'
  );

  await writeFile(
    join(TEMPLATES_DIR, 'each.tmpl'),
    '{{#each items}}{{this}}, {{/each}}',
    'utf-8'
  );

  await writeFile(
    join(TEMPLATES_DIR, 'malformed.tmpl'),
    'Hello {{name}',
    'utf-8'
  );

  // Create CLAUDE.md template for testing
  await writeFile(
    join(TEMPLATES_DIR, 'CLAUDE.md.tmpl'),
    `# {{projectName}}

*rill agent project generated by rill-create-agent*

## Project Structure

This project contains a rill agent with host integration.

| File | Purpose |
|------|---------|
| \`src/host.ts\` | Defines host functions available to the rill script |
| \`src/agent.rill\` | Main rill script containing agent logic |
| \`src/run.ts\` | Entry point that loads the script and executes it |

## Extension Namespaces

This project includes the following extensions:

| Namespace | Package | Documentation |
|-----------|---------|---------------|
{{#each extensions}}
| \`{{namespace}}\` | \`{{npmPackage}}\` | [Extension Docs](https://www.npmjs.com/package/{{npmPackage}}) |
{{/each}}

Extensions provide domain-specific host functions accessible via namespace prefixes in rill scripts.

## Documentation Links

- [rill Language Reference](@docs/ref-language.md) - Core language syntax and semantics
- [Host Integration Guide](@docs/integration-host.md) - Embedding rill in applications
- [Developing Extensions](@docs/integration-extensions.md) - Creating reusable host function packages

## Commands

Development commands for this project:

\`\`\`bash
{{packageManager}} start      # Run the agent script
{{packageManager}} run check  # Validate rill script syntax
\`\`\`

Use \`{{packageManager}} start\` to execute your agent. Edit \`src/agent.rill\` to modify agent behavior and \`src/host.ts\` to add custom host functions.`,
    'utf-8'
  );
});

afterAll(async () => {
  // Clean up only test-specific templates, preserve real templates
  const testTemplates = [
    'simple.tmpl',
    'conditional.tmpl',
    'each.tmpl',
    'malformed.tmpl',
    'nested.tmpl',
    'mixed.tmpl',
  ];

  for (const template of testTemplates) {
    const path = join(TEMPLATES_DIR, template);
    try {
      await rm(path, { force: true });
    } catch {
      // Ignore errors if file doesn't exist
    }
  }
});

// ============================================================
// TEMPLATE RENDERING TESTS
// ============================================================

describe('renderTemplate', () => {
  describe('basic rendering', () => {
    it('renders simple template with variables', async () => {
      const result = await renderTemplate('simple.tmpl', { name: 'World' });
      expect(result).toBe('Hello World!');
    });

    it('renders template with multiple variables', async () => {
      const result = await renderTemplate('package.json.tmpl', {
        projectName: 'my-app',
        extensionPackages: [
          '@rcrsr/rill-ext-anthropic',
          '@rcrsr/rill-ext-qdrant',
        ],
      });

      const parsed = JSON.parse(result);
      expect(parsed.name).toBe('my-app');
      expect(parsed.type).toBe('module');
      expect(parsed.dependencies['@rcrsr/rill-ext-anthropic']).toBe('latest');
      expect(parsed.dependencies['@rcrsr/rill-ext-qdrant']).toBe('latest');
    });

    it('handles empty variables object', async () => {
      const result = await renderTemplate('simple.tmpl', {});
      expect(result).toBe('Hello !');
    });
  });

  describe('Handlebars features', () => {
    it('supports conditional blocks with #if', async () => {
      const enabled = await renderTemplate('conditional.tmpl', {
        enabled: true,
      });
      expect(enabled).toBe('Feature enabled');

      const disabled = await renderTemplate('conditional.tmpl', {
        enabled: false,
      });
      expect(disabled).toBe('Feature disabled');
    });

    it('supports iteration with #each', async () => {
      const result = await renderTemplate('each.tmpl', {
        items: ['apple', 'banana', 'cherry'],
      });
      expect(result).toBe('apple, banana, cherry, ');
    });
  });

  describe('error handling - missing files', () => {
    it('throws FileSystemError for missing template', async () => {
      await expect(renderTemplate('nonexistent.tmpl', {})).rejects.toThrow(
        FileSystemError
      );

      await expect(renderTemplate('nonexistent.tmpl', {})).rejects.toThrow(
        'Template not found: nonexistent.tmpl'
      );
    });

    it('throws FileSystemError with correct error type', async () => {
      try {
        await renderTemplate('missing.tmpl', {});
        expect.fail('Should have thrown FileSystemError');
      } catch (err) {
        expect(err).toBeInstanceOf(FileSystemError);
        expect(err).toHaveProperty('name', 'FileSystemError');
      }
    });
  });

  describe('error handling - template syntax', () => {
    it('throws TemplateError for malformed template', async () => {
      await expect(
        renderTemplate('malformed.tmpl', { name: 'Test' })
      ).rejects.toThrow(TemplateError);
    });

    it('throws TemplateError with details', async () => {
      await expect(
        renderTemplate('malformed.tmpl', { name: 'Test' })
      ).rejects.toThrow('Template rendering failed:');
    });

    it('includes error type information', async () => {
      try {
        await renderTemplate('malformed.tmpl', { name: 'Test' });
        expect.fail('Should have thrown TemplateError');
      } catch (err) {
        expect(err).toBeInstanceOf(TemplateError);
        expect(err).toHaveProperty('name', 'TemplateError');
      }
    });
  });

  describe('edge cases', () => {
    it('handles nested objects in variables', async () => {
      await writeFile(
        join(TEMPLATES_DIR, 'nested.tmpl'),
        'User: {{user.name}}, Age: {{user.age}}',
        'utf-8'
      );

      const result = await renderTemplate('nested.tmpl', {
        user: { name: 'Alice', age: 30 },
      });
      expect(result).toBe('User: Alice, Age: 30');
    });

    it('handles special characters in variables', async () => {
      const result = await renderTemplate('simple.tmpl', {
        name: '<script>alert("xss")</script>',
      });
      // Handlebars HTML-escapes by default
      expect(result).toContain('&lt;script&gt;');
    });

    it('handles numeric and boolean values', async () => {
      await writeFile(
        join(TEMPLATES_DIR, 'mixed.tmpl'),
        'Count: {{count}}, Active: {{active}}',
        'utf-8'
      );

      const result = await renderTemplate('mixed.tmpl', {
        count: 42,
        active: true,
      });
      expect(result).toBe('Count: 42, Active: true');
    });
  });

  describe('CLAUDE.md template', () => {
    it('renders CLAUDE.md with extension table', async () => {
      const result = await renderTemplate('CLAUDE.md.tmpl', {
        projectName: 'test-agent',
        packageManager: 'pnpm',
        extensions: [
          { namespace: 'fetch', npmPackage: '@rcrsr/rill-ext-fetch' },
          { namespace: 'db', npmPackage: '@rcrsr/rill-ext-postgres' },
        ],
      });

      expect(result).toContain('# test-agent');
      expect(result).toContain('| `fetch` | `@rcrsr/rill-ext-fetch`');
      expect(result).toContain('| `db` | `@rcrsr/rill-ext-postgres`');
      expect(result).toContain('pnpm start');
      expect(result).toContain('pnpm run check');
    });

    it('renders CLAUDE.md with no extensions', async () => {
      const result = await renderTemplate('CLAUDE.md.tmpl', {
        projectName: 'minimal-agent',
        packageManager: 'npm',
        extensions: [],
      });

      expect(result).toContain('# minimal-agent');
      expect(result).toContain('npm start');
      expect(result).toContain('npm run check');
      // Extension table header should still be present
      expect(result).toContain('| Namespace | Package | Documentation |');
    });

    it('renders CLAUDE.md with different package managers', async () => {
      const pnpmResult = await renderTemplate('CLAUDE.md.tmpl', {
        projectName: 'agent',
        packageManager: 'pnpm',
        extensions: [],
      });
      expect(pnpmResult).toContain('pnpm start');

      const npmResult = await renderTemplate('CLAUDE.md.tmpl', {
        projectName: 'agent',
        packageManager: 'npm',
        extensions: [],
      });
      expect(npmResult).toContain('npm start');

      const yarnResult = await renderTemplate('CLAUDE.md.tmpl', {
        projectName: 'agent',
        packageManager: 'yarn',
        extensions: [],
      });
      expect(yarnResult).toContain('yarn start');
    });
  });
});

// ============================================================
// ERROR CLASS TESTS
// ============================================================

describe('FileSystemError', () => {
  it('extends Error', () => {
    const err = new FileSystemError('test');
    expect(err).toBeInstanceOf(Error);
  });

  it('sets name property', () => {
    const err = new FileSystemError('test');
    expect(err.name).toBe('FileSystemError');
  });

  it('preserves message', () => {
    const err = new FileSystemError('custom message');
    expect(err.message).toBe('custom message');
  });
});

describe('TemplateError', () => {
  it('extends Error', () => {
    const err = new TemplateError('test');
    expect(err).toBeInstanceOf(Error);
  });

  it('sets name property', () => {
    const err = new TemplateError('test');
    expect(err.name).toBe('TemplateError');
  });

  it('preserves message', () => {
    const err = new TemplateError('syntax error');
    expect(err.message).toBe('syntax error');
  });
});

// ============================================================
// HOST.TS.TMPL TESTS
// ============================================================

describe('host.ts.tmpl', () => {
  describe('renders with 2 extensions', () => {
    it('generates 4 sections in correct order', async () => {
      const result = await renderTemplate('host.ts.tmpl', {
        imports: [
          {
            factoryName: 'createAnthropicExtension',
            packageName: '@rcrsr/rill-ext-anthropic',
          },
          {
            factoryName: 'createQdrantExtension',
            packageName: '@rcrsr/rill-ext-qdrant',
          },
        ],
        extensions: [
          {
            namespace: 'ai',
            factoryName: 'createAnthropicExtension',
            configFields: [
              { name: 'api_key', value: 'process.env.ANTHROPIC_API_KEY' },
              { name: 'model', value: "'claude-sonnet-4-5-20250929'" },
            ],
          },
          {
            namespace: 'db',
            factoryName: 'createQdrantExtension',
            configFields: [
              { name: 'url', value: 'process.env.QDRANT_URL' },
              { name: 'collection', value: "'vectors'" },
            ],
          },
        ],
      });

      // Section 1: Imports
      expect(result).toContain("import 'dotenv/config';");
      expect(result).toContain('import {');
      expect(result).toContain('hoistExtension,');
      expect(result).toContain('createRuntimeContext,');
      expect(result).toContain('prefixFunctions,');
      expect(result).toContain("} from '@rcrsr/rill';");
      expect(result).toContain(
        "import { createAnthropicExtension } from '@rcrsr/rill-ext-anthropic';"
      );
      expect(result).toContain(
        "import { createQdrantExtension } from '@rcrsr/rill-ext-qdrant';"
      );

      // Section 2: Extension hoisting
      expect(result).toContain(
        "const ai = hoistExtension('ai', createAnthropicExtension({"
      );
      expect(result).toContain('api_key: process.env.ANTHROPIC_API_KEY,');
      expect(result).toContain("model: 'claude-sonnet-4-5-20250929',");
      expect(result).toContain(
        "const db = hoistExtension('db', createQdrantExtension({"
      );
      expect(result).toContain('url: process.env.QDRANT_URL,');
      expect(result).toContain("collection: 'vectors',");

      // Section 3: App functions
      expect(result).toContain(
        'const appFunctions: Record<string, HostFunctionDefinition> = {'
      );
      expect(result).toContain('// TODO: Add your custom host functions here');

      // Section 4: createHost export
      expect(result).toContain('export function createHost() {');
      expect(result).toContain('const functions = {');
      expect(result).toContain('...ai.functions,');
      expect(result).toContain('...db.functions,');
      expect(result).toContain("...prefixFunctions('app', appFunctions),");
      expect(result).toContain('const dispose = async () => {');
      expect(result).toContain('await ai.dispose?.();');
      expect(result).toContain('await db.dispose?.();');
      expect(result).toContain('return { functions, dispose };');
    });

    it('handles single extension', async () => {
      const result = await renderTemplate('host.ts.tmpl', {
        imports: [
          {
            factoryName: 'createAnthropicExtension',
            packageName: '@rcrsr/rill-ext-anthropic',
          },
        ],
        extensions: [
          {
            namespace: 'ai',
            factoryName: 'createAnthropicExtension',
            configFields: [
              { name: 'api_key', value: 'process.env.ANTHROPIC_API_KEY' },
            ],
          },
        ],
      });

      expect(result).toContain(
        "const ai = hoistExtension('ai', createAnthropicExtension({"
      );
      expect(result).toContain('...ai.functions,');
      expect(result).toContain('await ai.dispose?.();');
      expect(result).not.toContain('db');
    });

    it('handles no extensions', async () => {
      const result = await renderTemplate('host.ts.tmpl', {
        imports: [],
        extensions: [],
      });

      expect(result).toContain("import 'dotenv/config';");
      expect(result).toContain('const functions = {');
      expect(result).toContain("...prefixFunctions('app', appFunctions),");
      expect(result).toContain('const dispose = async () => {');
      expect(result).toContain('return { functions, dispose };');
    });
  });
});

// ============================================================
// RUN.TS.TMPL TESTS
// ============================================================

describe('run.ts.tmpl', () => {
  describe('imports and executes agent.rill', () => {
    it('generates complete execution script', async () => {
      const result = await renderTemplate('run.ts.tmpl', {});

      // Shebang
      expect(result).toContain('#!/usr/bin/env tsx');

      // Imports
      expect(result).toContain("import { readFile } from 'node:fs/promises';");
      expect(result).toContain(
        "import { parse, execute, createRuntimeContext } from '@rcrsr/rill';"
      );
      expect(result).toContain("import type { RillValue } from '@rcrsr/rill';");
      expect(result).toContain("import { createHost } from './host.js';");

      // Helper function
      expect(result).toContain('function formatOutput(value: RillValue):');
      expect(result).toContain("if (value === null) return 'null';");

      // Main function
      expect(result).toContain('async function main(): Promise<void> {');
      expect(result).toContain(
        "const source = await readFile('agent.rill', 'utf-8');"
      );
      expect(result).toContain('const ast = parse(source);');
      expect(result).toContain('const { functions, dispose } = createHost();');
      expect(result).toContain('const ctx = createRuntimeContext({');
      expect(result).toContain('functions,');
      expect(result).toContain('callbacks: {');
      expect(result).toContain(
        'onLog: (value) => console.log(formatOutput(value)),'
      );
      expect(result).toContain('const result = await execute(ast, ctx);');
      expect(result).toContain(
        "console.log('[Result]', formatOutput(result.value));"
      );
      expect(result).toContain('await dispose();');

      // Error handling
      expect(result).toContain('} catch (error: unknown) {');
      expect(result).toContain(
        'const message = error instanceof Error ? error.message :'
      );
      expect(result).toContain('process.exit(1);');

      // Main invocation
      expect(result).toContain('main();');
    });
  });
});
