#!/usr/bin/env bash
# Language arbiter lock.
#
# packages/core/tests/language/ is the language behaviour specification: the
# arbiter of what rill does. Per CLAUDE.md it is protected and changes only for
# language spec changes, never to make an implementation change pass.
#
# Two checks:
#   1. Every file under packages/core/tests/language/ matches its recorded
#      sha256, and no file was added or removed. Touching the arbiter therefore
#      requires regenerating the lock, which lands in the diff as an explicit,
#      named "the arbiter changed" line.
#   2. No skipped or exclusive tests anywhere under packages/core/tests/. A
#      .skip/.todo/.only turns a red test green without deleting it, which the
#      lock alone cannot see outside the arbiter.
#
# Why a committed snapshot rather than a diff against a base ref: a merge-base
# diff degenerates to a no-op on main, where merge-base equals HEAD. It also
# cannot see files added in CI, since `git ls-files --others` only ever fires in
# a working tree. A snapshot behaves identically on main, on a branch, and in a
# fresh checkout.
#
# This is a tripwire, not access control. Anyone can run --update. The point is
# that doing so is loud and named in the diff.
#
# Usage: scripts/check-test-lock.sh [--update]
#        --update  rewrite the lock from the working tree. A deliberate act:
#                  commit the result and say why in the PR.

set -euo pipefail
export LC_ALL=C # stable collation for sort and comm
# Without this, a set -e abort inside a $(...) assignment exits 1 printing
# nothing at all.
trap 'echo "FAIL: unexpected abort at line ${LINENO} (exit $?)" >&2' ERR
cd "$(dirname "$0")/.."

ARBITER_DIR=packages/core/tests/language
LOCK_FILE=packages/core/tests/language.lock
TEST_ROOT=packages/core/tests

UPDATE=0
for arg in "$@"; do
  case "$arg" in
    --update) UPDATE=1 ;;
    *)
      echo "unknown option: $arg" >&2
      exit 2
      ;;
  esac
done

# --cached --others --exclude-standard is tracked plus untracked-but-not-ignored,
# so a new arbiter file counts before it is ever committed.
mapfile -t FILES < <(git ls-files --cached --others --exclude-standard -- "$ARBITER_DIR" | sort)

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "FAIL: no files found under ${ARBITER_DIR}/. Wrong directory, or the arbiter was deleted wholesale."
  exit 1
fi
for f in "${FILES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "FAIL: arbiter file is tracked but missing from the working tree: $f"
    exit 1
  fi
done

ACTUAL=$(sha256sum "${FILES[@]}")

if [ "$UPDATE" -eq 1 ]; then
  {
    echo "# Language arbiter lock. Generated by: bash scripts/check-test-lock.sh --update"
    echo "#"
    echo "# packages/core/tests/language/ is the language behaviour specification."
    echo "# An entry changing here means the arbiter changed. That must be a language"
    echo "# spec change, never a fix to make an implementation change pass."
    echo "#"
    echo "# ${#FILES[@]} files."
    printf '%s\n' "$ACTUAL"
  } >"$LOCK_FILE"
  echo "Updated ${LOCK_FILE} (${#FILES[@]} files)."
  exit 0
fi

# 1. Arbiter matches the lock.
if [ ! -f "$LOCK_FILE" ]; then
  echo "FAIL: ${LOCK_FILE} is missing. Create it with: bash scripts/check-test-lock.sh --update"
  exit 1
fi
EXPECTED=$(grep -vE '^\s*(#|$)' "$LOCK_FILE" || true)

if [ "$ACTUAL" != "$EXPECTED" ]; then
  echo "FAIL: ${ARBITER_DIR}/ does not match ${LOCK_FILE}."
  echo
  EXP_PATHS=$(printf '%s\n' "$EXPECTED" | awk '{print $2}')
  ACT_PATHS=$(printf '%s\n' "$ACTUAL" | awk '{print $2}')
  ADDED=$(comm -13 <(printf '%s\n' "$EXP_PATHS") <(printf '%s\n' "$ACT_PATHS") || true)
  REMOVED=$(comm -23 <(printf '%s\n' "$EXP_PATHS") <(printf '%s\n' "$ACT_PATHS") || true)
  BOTH=$(comm -12 <(printf '%s\n' "$EXP_PATHS") <(printf '%s\n' "$ACT_PATHS") || true)
  if [ -n "$ADDED" ]; then printf '  added:    %s\n' $ADDED; fi
  if [ -n "$REMOVED" ]; then printf '  removed:  %s\n' $REMOVED; fi
  for p in $BOTH; do
    e=$(printf '%s\n' "$EXPECTED" | awk -v p="$p" '$2 == p {print $1}')
    a=$(printf '%s\n' "$ACTUAL" | awk -v p="$p" '$2 == p {print $1}')
    if [ "$e" != "$a" ]; then
      echo "  modified: $p"
    fi
  done
  echo
  echo "If this is a deliberate language spec change, accept it with:"
  echo "  bash scripts/check-test-lock.sh --update"
  echo "and commit ${LOCK_FILE} alongside, saying why in the PR."
  echo "If it is not, revert the change: the arbiter does not move to make code pass."
  exit 1
fi
echo "OK: ${ARBITER_DIR}/ matches the lock (${#FILES[@]} files)."

# 2. No skipped or exclusive tests.
SKIPPED=$(grep -rnE '\.skip\(|\.todo\(|\.only\(|\bxit\(' "$TEST_ROOT" || true)
if [ -n "$SKIPPED" ]; then
  echo "FAIL: skipped or exclusive tests found under ${TEST_ROOT}/:"
  echo "$SKIPPED"
  echo
  echo "A .skip/.todo/.only turns a red test green without deleting it. Remove it."
  exit 1
fi
echo "OK: no skipped or exclusive tests under ${TEST_ROOT}/."

echo "PASS: language arbiter lock holds"
