#!/usr/bin/env npx tsx
/**
 * Generate bundled language reference for runtime introspection
 *
 * Reads docs/99_llm-reference.txt and generates src/generated/introspection-data.ts
 * with exported constant for getLanguageReference() implementation.
 *
 * Usage:
 *   npx tsx scripts/generate-docs-bundle.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const SOURCE_FILE = 'docs/99_llm-reference.txt';
const OUTPUT_FILE = 'src/generated/introspection-data.ts';

function main(): void {
  const rootDir = path.resolve(
    path.dirname(new URL(import.meta.url).pathname),
    '..'
  );
  const sourcePath = path.join(rootDir, SOURCE_FILE);
  const outputPath = path.join(rootDir, OUTPUT_FILE);

  // Check source file exists
  if (!fs.existsSync(sourcePath)) {
    console.error(`ERROR: Source file not found: ${sourcePath}`);
    process.exit(1);
  }

  // Read source content
  const content = fs.readFileSync(sourcePath, 'utf-8');

  // Escape backticks and backslashes for template literal
  const escaped = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');

  // Generate output
  const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generate-docs-bundle.ts from ${SOURCE_FILE}

export const LANGUAGE_REFERENCE = \`${escaped}\`;
`;

  // Write output file
  fs.writeFileSync(outputPath, output, 'utf-8');

  console.log(`Generated ${OUTPUT_FILE} from ${SOURCE_FILE}`);
  console.log(`Content length: ${content.length} characters`);
}

main();
